import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://demo.nopcommerce.com/")
    page.get_by_role("textbox", name="Search store").click()
    page.get_by_role("textbox", name="Search store").fill("Apple MacBook Pro")
    page.get_by_role("textbox", name="Search store").press("Enter")
    page.get_by_role("link", name="Apple MacBook Pro", exact=True).click()
    page.locator("#add-to-cart-button-4").click()
    expect(page.get_by_text("The product has been added to")).to_be_visible()
    page.get_by_title("Close").click()
    page.get_by_role("link", name="Shopping cart (2)").click()
    expect(page.locator("#shopping-cart-form")
           ).to_contain_text("Apple MacBook Pro")
    page.get_by_role("checkbox", name="I agree with the terms of").check()
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("button", name="Checkout as Guest").click()
    page.get_by_role("textbox", name="First name:").click()
    page.get_by_role("textbox", name="First name:").fill("Antonella")
    page.get_by_role("textbox", name="Last name:").click()
    page.get_by_role("textbox", name="Last name:").fill("Pedreira")
    page.get_by_role("textbox", name="Email:").click()
    page.get_by_role("textbox", name="Email:").fill("antonella123@gmail.com")
    page.get_by_role("textbox", name="City:").click()
    page.get_by_role("textbox", name="City:").fill("miami")
    page.get_by_role("textbox", name="Address 1:").click()
    page.get_by_role("textbox", name="Address 1:").fill(
        "2516 NW 2nd Ave Miami FL 33127 Estados Unidos")
    page.get_by_label("State / province:").select_option("1726")
    page.get_by_role("textbox", name="Zip / postal code:").click()
    page.get_by_role("textbox", name="Zip / postal code:").fill("33127")
    page.get_by_role("textbox", name="Phone number:").click()
    page.get_by_role("textbox", name="Phone number:").fill("3055763334")
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("radio", name="Next Day Air ($0.00)").check()
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("radio", name="Check / Money Order Check /").check()
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("button", name="Confirm").click()
    expect(page.locator("#main")).to_contain_text(
        "Your order has been successfully processed!")
